name: build and deploy code

on: [push, pull_request]

jobs:
  job1:
    runs-on: macos-latest
    steps:
      - name: pull git repo
        uses: actions/checkout@v2
      - name: say hi to ryan
        uses: echo "hello ryan"





